# Generated by Django 5.2.10 on 2026-02-01 04:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='main', unique=True)),
                ('name', models.CharField(default='Main', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreestyleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('play_url', models.URLField(help_text='Direct MP4 URL or .m3u8 HLS URL')),
                ('artwork_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='For MP4: used for offset + looping. 0 = unknown.')),
                ('is_hls', models.BooleanField(default=False)),
                ('sponsor_title', models.CharField(blank=True, default='', max_length=140)),
                ('sponsor_subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('sponsor_url', models.URLField(blank=True, default='')),
                ('sponsor_image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('click_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='freestyle.channel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChannelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=True, help_text='True for live streams (.m3u8). False for MP4 rotation.')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry started playing')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='freestyle.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_entries', to='freestyle.freestylevideo')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=120)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='freestyle.channel')),
            ],
            options={
                'unique_together': {('channel', 'sid')},
            },
        ),
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=120)),
                ('reaction', models.CharField(choices=[('fire', 'Fire'), ('nah', 'Nah')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='freestyle.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='freestyle.freestylevideo')),
            ],
            options={
                'unique_together': {('channel', 'video', 'client_id')},
            },
        ),
    ]
