# Generated by Django 5.2.10 on 2026-01-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('reaction', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reactions', to='freestyle.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='freestyle.freestylevideo')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('channel', 'video', 'client_id')},
            },
        ),
        migrations.DeleteModel(
            name='ChatReaction',
        ),
    ]
