# Generated by Django 5.2.10 on 2026-02-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freestylevideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='play_url',
            field=models.URLField(blank=True, default='', help_text='Direct MP4 URL or .m3u8 HLS URL (auto-set if you upload a file)'),
        ),
    ]
