# Generated by Django 6.0.1 on 2026-01-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='freestyle.channelentry')),
            ],
        ),
    ]
