# Generated by Django 5.2.10 on 2026-01-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0002_videoreaction_delete_chatreaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='has_played_once',
        ),
        migrations.AddField(
            model_name='freestylevideo',
            name='captions_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='reaction',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='videoreaction',
            constraint=models.UniqueConstraint(fields=('channel', 'video', 'client_id'), name='uniq_vote_per_client_per_video'),
        ),
    ]
