# Generated by Django 5.2.10 on 2026-02-01 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0002_freestylevideo_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freestylevideo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freestyle_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=True, help_text='True for live streams. False for MP4 rotation.'),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled for uploaded MP4 if ffprobe is available.'),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='is_hls',
            field=models.BooleanField(default=False, help_text='Check this ONLY if play_url is an HLS stream (.m3u8). For uploaded MP4, leave unchecked.'),
        ),
    ]
