# Generated by Django 5.2.10 on 2026-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0003_alter_videoreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videoreaction',
            name='uniq_vote_per_client_per_video',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='captions_words',
        ),
        migrations.AddField(
            model_name='channelentry',
            name='has_played_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together={('channel', 'video', 'client_id')},
        ),
    ]
