# Generated by Django 6.0.1 on 2026-01-27 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0003_freestylevideo_creator_freestylevideo_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreestyleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='freestyle_submissions/')),
                ('playback_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freestyle.freestylevideo')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freestyle_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freestyle_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
