# Generated by Django 5.2.10 on 2026-02-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0003_freestylevideo_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Auto-filled for uploaded MP4. 0 = unknown.'),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='is_hls',
            field=models.BooleanField(default=False, help_text='Check ONLY if play_url is an HLS stream (.m3u8). For uploaded MP4, leave unchecked.'),
        ),
    ]
