# Generated by Django 5.2.10 on 2026-01-29 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0004_remove_videoreaction_uniq_vote_per_client_per_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='videoreaction',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='has_played_once',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='video',
        ),
        migrations.AddField(
            model_name='channel',
            name='current_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='freestyle.channelentry'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='username',
            field=models.CharField(default='guest', max_length=32),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='playback_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='client_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='videoreaction',
            constraint=models.UniqueConstraint(fields=('channel', 'video', 'client_id'), name='uniq_vote_per_client_per_video'),
        ),
    ]
