# Generated by Django 5.2.10 on 2026-02-01 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0004_alter_freestylevideo_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True for live streams (.m3u8). False for MP4 rotation.'),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='is_hls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='play_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
