# Generated by Django 6.0.1 on 2026-01-27 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0004_freestylesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
