# Generated by Django 5.2.10 on 2026-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0005_alter_channelentry_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='playback_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
