# Generated by Django 5.2.10 on 2026-02-01 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0005_alter_channelentry_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='rotation_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True ONLY for live streams (.m3u8). False for MP4 playlist rotation.'),
        ),
    ]
