# Generated by Django 6.0.1 on 2026-01-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0005_channel_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='freestylesubmission',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='freestylesubmission',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='freestylesubmission',
            name='playback_url',
        ),
        migrations.RemoveField(
            model_name='freestylesubmission',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='freestylesubmission',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='channelentry',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='freestylesubmission',
            name='created_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_submissions', to='freestyle.freestylevideo'),
        ),
        migrations.AlterField(
            model_name='freestylesubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='playback_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playbackevent',
            name='event_type',
            field=models.CharField(default='complete', max_length=20),
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='first_played_at',
        ),
    ]
