# Generated by Django 5.2.10 on 2026-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0006_channel_rotation_started_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True for live streams (.m3u8). False for MP4 rotation.'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('channel', 'sid'), name='uniq_presence_channel_sid'),
        ),
        migrations.AddConstraint(
            model_name='videoreaction',
            constraint=models.UniqueConstraint(fields=('channel', 'video', 'client_id'), name='uniq_reaction_once'),
        ),
    ]
