# Generated by Django 5.2.10 on 2026-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0006_alter_freestylevideo_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestylevideo',
            name='playback_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
