# Generated by Django 5.2.10 on 2026-01-29 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0007_alter_freestylevideo_playback_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['channel', 'position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Main', max_length=120),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='main', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='playback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='client_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='reaction',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='videoreaction',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.freestylevideo'),
        ),
    ]
