# Generated by Django 5.2.10 on 2026-01-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0007_freestylevideo_captions_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestylevideo',
            name='captions_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
