# Generated by Django 5.2.10 on 2026-02-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0007_alter_presence_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='presence',
            name='uniq_presence_channel_sid',
        ),
        migrations.RemoveConstraint(
            model_name='videoreaction',
            name='uniq_reaction_once',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='rotation_started_at',
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('channel', 'sid')},
        ),
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together={('channel', 'video', 'client_id')},
        ),
    ]
