# Generated by Django 5.2.10 on 2026-01-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0008_alter_freestylevideo_captions_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, default='main', max_length=64)),
                ('username', models.CharField(max_length=48)),
                ('message', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['channel', 'id'], name='freestyle_c_channel_71e6a0_idx'), models.Index(fields=['channel', 'created_at'], name='freestyle_c_channel_0038f7_idx')],
            },
        ),
    ]
