# Generated by Django 5.2.10 on 2026-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0008_remove_presence_uniq_presence_channel_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True for live streams (.m3u8). False for MP4 playlist rotation.'),
        ),
    ]
