# Generated by Django 5.2.10 on 2026-01-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0009_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['position', 'id']},
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='has_played_once',
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='play_count',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freestylevideo',
            name='captions_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, default='main', max_length=64)),
                ('video_id', models.CharField(db_index=True, max_length=32)),
                ('user_key', models.CharField(db_index=True, max_length=64)),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'video_id', 'emoji'], name='freestyle_c_channel_d5a256_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'video_id', 'user_key'), name='uniq_reaction_user_video')],
            },
        ),
    ]
