# Generated by Django 5.2.10 on 2026-02-01 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0009_alter_channelentry_is_live'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='started_at',
        ),
        migrations.AddField(
            model_name='channel',
            name='schedule_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True ONLY for live streams (.m3u8). Keep False for MP4 rotation.'),
        ),
    ]
