# Generated by Django 5.2.10 on 2026-01-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0009_fix_missing_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='current_entry',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='started_at',
        ),
        migrations.AlterUniqueTogether(
            name='channelentry',
            unique_together={('channel', 'position')},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='username',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='playback_url',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='channel',
            name='start_epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='guest_name',
            field=models.CharField(default='Guest', max_length=64),
        ),
        migrations.AddField(
            model_name='freestylevideo',
            name='captions_vtt',
            field=models.FileField(blank=True, null=True, upload_to='freestyle_captions/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freestyle.freestylevideo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='freestyle_videos/'),
        ),
        migrations.DeleteModel(
            name='VideoReaction',
        ),
        migrations.RemoveField(
            model_name='channelentry',
            name='is_active',
        ),
    ]
