# Generated by Django 5.2.10 on 2026-02-01 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0010_alter_channelentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='channelentry',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='channel',
            name='schedule_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Playlist timing anchor. All viewers sync to this clock.'),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False, help_text='True for live streams (.m3u8). False for MP4 playlist rotation.'),
        ),
    ]
