# Generated by Django 5.2.10 on 2026-01-30 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0010_alter_channelentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='start_epoch',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='channel',
            name='schedule_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='name',
            field=models.CharField(default='Guest', max_length=32),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.freestylevideo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='file',
            field=models.FileField(upload_to='freestyle_videos/'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=8)),
                ('video_start_epoch', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.channel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freestyle.freestylevideo')),
            ],
            options={
                'unique_together': {('channel', 'video', 'session_key', 'video_start_epoch')},
            },
        ),
    ]
