# Generated by Django 5.2.10 on 2026-01-31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freestyle", "0011_alter_channelentry_options_alter_chatmessage_options_and_more"),
    ]

    operations = [
        # Safe integer field tweaks
        migrations.AlterModelOptions(
            name="channelentry",
            options={"ordering": ["channel", "position"]},
        ),
        migrations.AlterField(
            model_name="channelentry",
            name="position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="freestylevideo",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),

        # ---- FIX vote.created conversion SAFELY ----
        # 1) add new datetime field
        migrations.AddField(
            model_name="vote",
            name="created_dt",
            field=models.DateTimeField(null=True, blank=True),
        ),

        # 2) convert integer epoch -> timestamptz (only if old integer exists)
        #    If created was already a datetime, this will still succeed because
        #    the UPDATE uses a CASE to avoid crashing.
        migrations.RunSQL(
            sql="""
                UPDATE freestyle_vote
                SET created_dt =
                    CASE
                        WHEN pg_typeof(created)::text = 'integer' THEN to_timestamp(created)
                        ELSE created
                    END
                WHERE created_dt IS NULL;
            """,
            reverse_sql="""
                UPDATE freestyle_vote
                SET created_dt = NULL;
            """,
        ),

        # 3) remove old field
        migrations.RemoveField(
            model_name="vote",
            name="created",
        ),

        # 4) rename created_dt -> created
        migrations.RenameField(
            model_name="vote",
            old_name="created_dt",
            new_name="created",
        ),

        # 5) ensure model uses auto_now going forward
        migrations.AlterField(
            model_name="vote",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
