# Generated by Django 5.2.10 on 2026-02-01 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0011_alter_channelentry_options_channelentry_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freestylevideo',
            name='sponsor_image_url',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='sponsor_subtitle',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='sponsor_title',
        ),
        migrations.RemoveField(
            model_name='freestylevideo',
            name='sponsor_url',
        ),
        migrations.AlterField(
            model_name='channel',
            name='schedule_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
