# Generated by Django 5.2.10 on 2026-01-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0011_alter_channelentry_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['channel', 'position']},
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='freestylevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
