# Generated by Django 5.2.10 on 2026-01-31 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0012_alter_channelentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelentry',
            options={'ordering': ['channel_id', 'position']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='channelentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='schedule_epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='channelentry',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_entries', to='freestyle.freestylevideo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='freestyle.channel'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='kind',
            field=models.CharField(choices=[('fire', 'Fire'), ('nah', 'Nah')], max_length=8),
        ),
        migrations.AlterField(
            model_name='vote',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='freestyle.freestylevideo'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='video_start_epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='channelentry',
            constraint=models.UniqueConstraint(fields=('channel', 'position'), name='uniq_channel_position'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('channel', 'video', 'session_key', 'video_start_epoch'), name='uniq_vote_per_session_start'),
        ),
    ]
